import "./globals.css";
import Navbar from "./components/Navbar";
import { ToastContainer } from "react-toastify";
import AuthContextProvider from "./contexts/AuthContext";

export const metadata = {
  title: "Hotel Booking",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ToastContainer/>
        <AuthContextProvider>
          <Navbar/>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}